import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FileText, Building2, Shield, Eye, Cookie, Lock, UserCheck, Gavel, Mail, MapPin } from "lucide-react";

const Privacy = () => {
  const sections = [
    {
      icon: FileText,
      title: "1. GENERAL",
      items: [
        {
          label: "a) Electronic Record",
          content: "This document is an electronic record in terms of the Information Technology Act, 2000 and the Digital Personal Data Protection (DPDP) Act, 2023. This record is generated by a computer system and does not require physical or digital signatures.",
        },
        {
          label: "b) Proprietorship",
          content: 'The domain name www.jointlly.in ("Website") and the Jointlly Mobile Application are owned and operated by Jointlly Tech Pvt Ltd, a company incorporated under the Companies Act, 2013, with its registered office in Bengaluru, Karnataka.',
        },
        {
          label: "c) Compliance",
          content: "This Policy is published in accordance with Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 and the DPDP Act 2023, which require the publication of a Privacy Policy for access or usage of the Platform.",
        },
      ],
    },
    {
      icon: Shield,
      title: "2. DATA COLLECTION & CONSENT (DPDP ACT 2023)",
      items: [
        {
          label: "a) Affirmative Consent",
          content: 'By using the Website and providing information, the User provides clear affirmative consent to Jointlly Pvt Ltd (the "Data Fiduciary") to collect and process personal data for the purposes of matchmaking.',
        },
        {
          label: "b) Information Collected",
          content: "We collect information provided by you, including but not limited to: Name, Phone Number, Email, Property ID (PID), Property Location, Plot Size, and project preferences.",
        },
        {
          label: "c) Automatic Tracking",
          content: "We may automatically track information based on your IP address and behavior on the Website to improve safety and user experience. This includes browser information and URL navigation history.",
        },
      ],
    },
    {
      icon: Building2,
      title: "3. PURPOSE OF PROCESSING & DATA SHARING",
      items: [
        {
          label: "a) Matchmaking Infrastructure",
          content: "The primary purpose of data collection is to facilitate a discovery match between Landowners and Construction Professionals.",
        },
        {
          label: 'b) The "Rule of Five"',
          content: "To protect User privacy while ensuring choice, Jointlly will share the User's contact and property details with a maximum of five (5) matching professionals at any given time.",
        },
        {
          label: "c) Extended Matching",
          content: "If the User requires more options, a manual request must be initiated, which constitutes a fresh consent for further data sharing.",
        },
        {
          label: "d) Legal Disclosure",
          content: "We may disclose personal information if required by law to respond to subpoenas, court orders, or requests from the Data Protection Board of India.",
        },
      ],
    },
    {
      icon: Eye,
      title: "4. USER RIGHTS (DATA PRINCIPAL RIGHTS)",
      items: [
        {
          label: "Right to Access",
          content: "You may request a summary of the personal data being processed.",
        },
        {
          label: "Right to Correction/Erasure",
          content: "You may request the correction of inaccurate data or the erasure of your data once the matchmaking purpose is fulfilled.",
        },
        {
          label: "Right to Withdraw Consent",
          content: 'You may withdraw your consent at any time via the "Consent Manager" in your account settings. Upon withdrawal, Jointlly will cease processing your data within 48 hours.',
        },
      ],
    },
    {
      icon: Cookie,
      title: "5. COOKIES",
      items: [
        {
          label: "Cookie Usage",
          content: "Jointlly uses cookies to analyze web page flow, measure promotional effectiveness, and promote trust. Some features are only available through the use of cookies. You may decline cookies through your browser settings, though this may limit platform functionality.",
        },
      ],
    },
    {
      icon: Lock,
      title: "6. SECURITY",
      items: [
        {
          label: "Data Protection",
          content: "Jointlly Tech Pvt Ltd employs industry-standard encryption to protect data during transmission. We do not store credit/debit card information; all payments are processed through RBI-authorized, PCI-DSS compliant third-party gateways (e.g., Razorpay/Stripe).",
        },
      ],
    },
    {
      icon: UserCheck,
      title: "7. GRIEVANCE REDRESSAL & DATA PROTECTION OFFICER",
      items: [
        {
          label: "Contact Information",
          content: "In accordance with the IT Act 2000 and DPDP Act 2023, the details of the Grievance Officer and Data Protection Officer (DPO) are:",
          details: [
            "Name: Hemanth Murthy",
            "Email: grievance@jointlly.in",
            "Address: Banashankari, Bengaluru 560061",
          ],
        },
      ],
    },
    {
      icon: Gavel,
      title: "8. DISPUTE RESOLUTION & JURISDICTION",
      items: [
        {
          label: "a) Mediation",
          content: "Disputes shall first be attempted to be resolved amicably within 30 days.",
        },
        {
          label: "b) Arbitration",
          content: "Unresolved disputes shall be referred to a sole arbitrator appointed by the Company. The seat of arbitration shall be Bengaluru, India, and the language shall be English.",
        },
        {
          label: "c) Jurisdiction",
          content: "This Policy is governed by the laws of India. The Courts at Bengaluru shall have exclusive jurisdiction.",
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-background overflow-x-hidden">
      <Navbar />
      <div className="absolute inset-0 bg-gradient-to-br from-emerald-50/70 via-green-50/60 to-teal-50/70" />
      <div className="absolute inset-0 jointlly-grid opacity-40" />
      <div className="relative z-10 pt-24 md:pt-28 pb-16 md:pb-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">
              <span className="text-gradient-primary">Privacy Policy</span>
            </h1>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Jointlly Pvt Ltd
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </motion.div>

          {/* Privacy Policy Sections */}
          <div className="space-y-8">
            {sections.map((section, sectionIndex) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: sectionIndex * 0.1 }}
                  className="glass-card p-6 md:p-8"
                >
                  <div className="flex items-start gap-4 mb-6">
                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center flex-shrink-0">
                      <Icon className="w-6 h-6 text-primary" />
                    </div>
                    <h2 className="text-2xl md:text-3xl font-bold text-foreground flex-1">
                      {section.title}
                    </h2>
                  </div>

                  <div className="space-y-6 ml-0 md:ml-16">
                    {section.items.map((item, itemIndex) => (
                      <div key={itemIndex} className="space-y-2">
                        <h3 className="font-semibold text-foreground text-lg">
                          {item.label}
                        </h3>
                        <p className="text-muted-foreground leading-relaxed">
                          {item.content}
                        </p>
                        {item.details && (
                          <div className="mt-3 space-y-2 pl-4 border-l-2 border-primary/20">
                            {item.details.map((detail, detailIndex) => (
                              <div key={detailIndex} className="flex items-start gap-2">
                                {detail.startsWith("Email:") && <Mail className="w-4 h-4 text-primary mt-1 flex-shrink-0" />}
                                {detail.startsWith("Address:") && <MapPin className="w-4 h-4 text-primary mt-1 flex-shrink-0" />}
                                {!detail.startsWith("Email:") && !detail.startsWith("Address:") && <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />}
                                <p className="text-muted-foreground">{detail}</p>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* Footer Note */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.8 }}
            className="mt-12 p-6 rounded-xl bg-blue-500/10 border border-blue-500/20"
          >
            <p className="text-sm text-muted-foreground text-center">
              <strong className="text-foreground">Your Privacy Matters:</strong> We are committed to protecting your personal data in accordance with the DPDP Act 2023. For any privacy-related concerns or to exercise your rights, please contact our Data Protection Officer at grievance@jointlly.in
            </p>
          </motion.div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Privacy;
