import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FileText, Scale, Users, Shield, CreditCard, Database, AlertTriangle, Gavel } from "lucide-react";

const Terms = () => {
  const sections = [
    {
      icon: FileText,
      title: "1. GENERAL & NATURE OF SERVICE",
      items: [
        {
          label: "a) Electronic Record",
          content: "This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder. This record is generated by a computer system and does not require physical or digital signatures.",
        },
        {
          label: "b) Intermediary Status",
          content: 'Jointlly ("the Website/App") is an Intermediary as defined under Section 2(1)(w) of the IT Act, 2000. We act solely as a technology platform to facilitate the discovery of real estate opportunities (Joint Development, Construction, Renovations) by matching Landowners ("Clients") with Builders/Architects ("Vendors").',
        },
        {
          label: "c) Neutral Pipeline",
          content: 'You acknowledge that Jointlly is not a real estate developer, builder, or legal consultant. We do not provide "Professional Advice." Any data, FAR calculations, or matching results are generated algorithmically for informational purposes only.',
        },
      ],
    },
    {
      icon: Users,
      title: "2. THE MATCHMAKING SERVICE",
      items: [
        {
          label: "Project Posting",
          content: "Clients can post property details for a nominal 'Serious Intent Fee.'",
        },
        {
          label: "Professional Matching",
          content: "Vendors can access project leads upon payment of a 'Gatekeeper/Token Fee.'",
        },
        {
          label: "Neutral Discovery",
          content: "We facilitate the exchange of contact information between a maximum of three (3) matching Vendors and one (1) Client.",
        },
        {
          label: "No Endorsement",
          content: "The appearance of a Vendor on the platform does not constitute an endorsement or guarantee of their financial solvency or construction quality.",
        },
      ],
    },
    {
      icon: Scale,
      title: "3. RERA COMPLIANCE & USER OBLIGATIONS",
      items: [
        {
          label: "a) Mandatory RERA",
          content: "For projects exceeding 500 sq. meters or 8 units, the Vendor must provide a valid RERA Project Registration Number. Jointlly will not facilitate matches for non-compliant large-scale projects.",
        },
        {
          label: "b) Agent Status",
          content: "Jointlly is a registered Real Estate Agent under Karnataka RERA (Reg No: [Pending]).",
        },
        {
          label: "c) Due Diligence",
          content: "The User (Client) expressly agrees that it is their sole responsibility to conduct site visits, verify the Vendor's past projects, and check legal titles before entering into a contract. Jointlly is not a party to any contract signed between a Client and a Vendor.",
        },
      ],
    },
    {
      icon: CreditCard,
      title: "4. CHARGES & REFUNDS",
      items: [
        {
          label: "a) Platform Access Fee",
          content: "Clients may be charged a non-refundable 'Serious Intent Fee' (e.g., ₹99) to verify lead quality.",
        },
        {
          label: "b) Vendor Token Fee",
          content: "Vendors pay a 'Gatekeeper Fee' to access lead details. This fee is for access only and does not guarantee a successful contract conversion.",
        },
        {
          label: "c) Success Fee",
          content: "High-value matches (Joint Development) may be subject to a success fee (0.5% - 2%) as per separate Vendor Agreements.",
        },
        {
          label: "d) Refunds",
          content: "Fees are generally non-refundable unless the lead data is proven to be fraudulent (e.g., nonexistent phone number/property) within 48 hours of matching.",
        },
      ],
    },
    {
      icon: Database,
      title: "5. DATA PRIVACY & DPDP ACT 2023",
      items: [
        {
          label: "a) Consent",
          content: "By using Jointlly, you provide affirmative consent for us to process your Property ID (PID), Location, and Contact details.",
        },
        {
          label: "b) Purpose",
          content: 'Data is processed strictly for the purpose of "Matchmaking."',
        },
        {
          label: "c) Data Erasure",
          content: "Users have the right to request erasure of their data once a match is concluded or if they wish to withdraw from the platform, subject to statutory tax record requirements.",
        },
      ],
    },
    {
      icon: AlertTriangle,
      title: "6. LIMITATION OF LIABILITY",
      items: [
        {
          label: "a) Intermediary Protection",
          content: "As per Section 79 of the IT Act, Jointlly shall not be liable for any third-party information, data, or communication links made available by us.",
        },
        {
          label: "b) Abetment of Fraud",
          content: "Jointlly shall not be held liable for any scam, financial loss, or construction defect caused by a Vendor. Our liability is limited to the verification of the identity documents (PAN/GST) provided by the Vendor at the time of onboarding.",
        },
        {
          label: "c) Cap on Liability",
          content: "In any event, the total liability of Jointlly to a user shall not exceed the total fees paid by the user to the platform in the preceding three (3) months.",
        },
      ],
    },
    {
      icon: Gavel,
      title: "7. DISPUTE RESOLUTION",
      items: [
        {
          label: "a) Two-Step Mechanism",
          content: "Any dispute shall first be attempted to be resolved via Mediation within 30 days.",
        },
        {
          label: "b) Arbitration",
          content: "If mediation fails, the dispute shall be referred to a sole arbitrator appointed by Jointlly. The seat of arbitration shall be Bengaluru, Karnataka.",
        },
        {
          label: "c) Jurisdiction",
          content: "These terms are governed by the laws of India, and the courts of Bengaluru shall have exclusive jurisdiction.",
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-background overflow-x-hidden">
      <Navbar />
      <div className="absolute inset-0 bg-gradient-to-br from-emerald-50/70 via-green-50/60 to-teal-50/70" />
      <div className="absolute inset-0 jointlly-grid opacity-40" />
      <div className="relative z-10 pt-24 md:pt-28 pb-16 md:pb-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">
              <span className="text-gradient-primary">Terms of Use</span>
            </h1>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Jointlly Pvt Ltd
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </motion.div>

          {/* Terms Sections */}
          <div className="space-y-8">
            {sections.map((section, sectionIndex) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: sectionIndex * 0.1 }}
                  className="glass-card p-6 md:p-8"
                >
                  <div className="flex items-start gap-4 mb-6">
                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center flex-shrink-0">
                      <Icon className="w-6 h-6 text-primary" />
                    </div>
                    <h2 className="text-2xl md:text-3xl font-bold text-foreground flex-1">
                      {section.title}
                    </h2>
                  </div>

                  <div className="space-y-6 ml-0 md:ml-16">
                    {section.items.map((item, itemIndex) => (
                      <div key={itemIndex} className="space-y-2">
                        <h3 className="font-semibold text-foreground text-lg">
                          {item.label}
                        </h3>
                        <p className="text-muted-foreground leading-relaxed">
                          {item.content}
                        </p>
                      </div>
                    ))}
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* Footer Note */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.7 }}
            className="mt-12 p-6 rounded-xl bg-amber-500/10 border border-amber-500/20"
          >
            <p className="text-sm text-muted-foreground text-center">
              <strong className="text-foreground">Important:</strong> By using Jointlly's services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our platform.
            </p>
          </motion.div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Terms;
